### ISSUE TITLE
problem with images and seph-osd on conjure-up installation

### ISSUE THREAD

**Issue by heinsaris** [lxc/nova-lxd#138]
I have installed openstack via conjure-up using the nova-lxd option and I have (at least) two related? issues:

- images are always in Saving state and therefore I cannot create instances
- ceph-osd is blocked saying 'No block devices detected using current configuration

The hardware is a PC running Ubuntu Server 16.04 (Xenial) on a ext4 filesystem, with a ZFS block device for LXD.

I have reinstalled twice already and the problem is always the same.

Any help is welcome.

**Comment by javacruft** [comment]
The final release of Ceph Jewel introduced a startup check which is currently blocking ceph-osd startup when using directory based OSD's under LXD:

  https://bugs.launchpad.net/charms/+source/ceph-osd/+bug/1580320

Working on fixes atm; the current master branch will work, will take ~1 day or so to get that released as an update.

**Comment by jamesbeedy** [comment]
Ceph jewel lost support for ext4, which is the type of extent getting created I top of your zfs array and passed through to your containers. The workaround for this, is to create your underlying filesystem on lvm, and set the lxc lvm config to use the lvm volumegroup you created, and lxc storage.lvm_fstype to be xfs. The fix for this has been released, and is in charm-ceph-osd master.
