### ISSUE TITLE
irqbalance spam

### ISSUE THREAD

**Issue by jamesbeedy** [lxc/nova-lxd#142]
Trusty lxd syslog getting spammed with:

2016-05-24T11:32:30.002201-07:00 dhc-staging-app80 /usr/sbin/irqbalance: WARNING, didn't collect load info for all cpus, balancing is broken

**Comment by jamesbeedy** [comment]
Setting ENABLED=0 in /etc/default/irqbalance fixes. Could this be set by default in the root-tar imgs?

**Comment by rockstar** [comment]
Can you re-file this issue with https://github.com/lxc/lxd ?

**Comment by stgraber** [comment]
Actually, the issue is that irqbalance shouldn't start in containers.

This would be an irqbalance packaging bug which must be filed at https://launchpad.net/ubuntu/+source/irqbalance/+filebug

I know that irqbalance was changed to be clever in that regard in Xenial, I guess something similar should be done for trusty.
