### ISSUE TITLE
Provide a Nova option to manage "security.nesting" on LXD Compute Nodes

### ISSUE THREAD

**Issue by tmartinx** [lxc/nova-lxd#60]
Guys,

Currently, LXD have a great feature, called "Nested LXD", where we can run LXD containers, inside a LXD container!

The option enable it is: "security.nesting 1"

However, this needs to be configured on the host, right after initializing the LXD container, like this:

    lxc init wily w1
    lxc config set w1 security.nesting 1
    lxc start w1

So, we might need a way in Nova Compute LXD, to set "security.nesting 1" for each container that it launches... So, the LXD in LXD will work on OpenStack easily!

Thread on Ubuntu mail list about this:

https://lists.ubuntu.com/archives/ubuntu-server/2015-October/007124.html
https://lists.ubuntu.com/archives/ubuntu-server/2015-October/007127.html

Thanks!
Thiago

**Comment by fawadkhaliq** [comment]
Thiago, I don't quite understand where nested LXD will fit in Nova world. Can you please elaborate?

**Comment by tpouyer** [comment]
You will need to specify "additional flavour properties" on the image you upload to Glance  Those flavour properties will be used by nova-lxd to set either nested privileges or uncontained privileges or both.  i.e. :

https://github.com/lxc/nova-lxd/commit/20ab69d173a0866a5b217ba6887bab96cd4f3ab4

line 165 and line 170

You can do this be adjusting the flavour in your OpenStack to add these addtional properties specific to LXD:

'lxd_nested_allowed'
'lxd_privileged_allowed'

all other properties are derived from the flavour like:

cpu
memory
disk

hope that helps you out a bit.

**Comment by zulcss** [comment]
This has been fixed

**Comment by peter-slovak** [comment]
Just a note - if you use the ComputeCapabilitiesFilter for scheduling, the added options (lxd_nested_allowed and lxd_privileged_allowed) will cause nova-scheduler to treat them as "host capabilities". And since no host will match, the scheduling will fail.

The obvious solution is not to use ComputeCapabilitiesFilter if not needed. For the rest of the cases, would you please consider moving these extra_specs into a namespace of their own? For example, `lxd:nested_allowed` and `lxd:privileged_allowed` would work fine, because the CCF ignores such namespaces during scheduling. Thanks a lot.
